/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CssInJsTest {}
  interface ThemeProvider {
    'theme': {};
  }
}

declare global {


  interface HTMLCssInJsTestElement extends Components.CssInJsTest, HTMLStencilElement {}
  var HTMLCssInJsTestElement: {
    prototype: HTMLCssInJsTestElement;
    new (): HTMLCssInJsTestElement;
  };

  interface HTMLThemeProviderElement extends Components.ThemeProvider, HTMLStencilElement {}
  var HTMLThemeProviderElement: {
    prototype: HTMLThemeProviderElement;
    new (): HTMLThemeProviderElement;
  };
  interface HTMLElementTagNameMap {
    'css-in-js-test': HTMLCssInJsTestElement;
    'theme-provider': HTMLThemeProviderElement;
  }
}

declare namespace LocalJSX {
  interface CssInJsTest extends JSXBase.HTMLAttributes<HTMLCssInJsTestElement> {}
  interface ThemeProvider extends JSXBase.HTMLAttributes<HTMLThemeProviderElement> {
    'theme'?: {};
  }

  interface IntrinsicElements {
    'css-in-js-test': CssInJsTest;
    'theme-provider': ThemeProvider;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


